config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, length: {maximum: 400}
  validates_presence_of :content, :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  validates_presence_of :name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FirstRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
   
    <%= yield %>
    
    <footer>
      <div class="container">
        <a href="http://railsgirls.com/beograd.html" target="_blank"><h5> &copy; Rails Girls Beograd <%= Time.now.year %></h5></a>
      </div>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_area :content, class: 'form-control', placeholder: 'Write Your Post Here' %>
  </div>

  <div class="form-group">
    <%= form.number_field :user_id, class: 'form-control', placeholder: 'Enter a User Id Integer Number Here' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-8"><br>
  <h3>Edit this Post</h3><br>

  <%= render 'form', post: @post %>

  <%= link_to 'View this Post', @post, class: 'btn btn-outline-info' %> 
  <%= link_to 'Back to all Posts', posts_path, class: 'btn btn-outline-primary' %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing of all Posts</h3><br>
<div class="table-responsive">

  <table class="table table-condensed table-bordered">
    <thead>
      <tr class="table-info">
        <th>Content</th>
        <th>User</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.content %></td>
          <td><%= post.user.name %></td>
          <td><%= link_to 'Show Post', post, class: 'btn btn-outline-info' %></td>
          <td><%= link_to 'Edit Post', edit_post_path(post), class: 'btn btn-outline-warning' %></td>
          <td><%= link_to 'Delete Post', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Write a new Post', new_post_path, class: 'btn btn-outline-primary' %><br><br>
  <%= link_to 'View all Users', users_path, class: 'btn btn-outline-primary' %>
</div>

app/views/posts/new.html.erb
<div class="col-md-8"><br>
  <h3>Write a new Post</h3><br>

  <%= render 'form', post: @post %>

  <%= link_to 'Back to all Posts', posts_path, class: 'btn btn-outline-primary' %>
</div>

app/views/posts/show.html.erb
<div class="col-md-8">
  <p id="notice"><%= notice %></p>

  <br>
  <p>
    <strong>Post Content:</strong><br><br>
    <%= @post.content %>
  </p>
  
  <p>
    <strong>Posted by:</strong>
    <%= @post.user.name %>
  </p>
  <br>

  <%= link_to 'Edit this Post', edit_post_path(@post), class: 'btn btn-outline-warning' %>
  <%= link_to 'Back to all Posts', posts_path, class: 'btn btn-outline-primary' %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter Your Name'  %>
  </div>

  <div class="form-group">
    <%= form.text_field :email, class: 'form-control', placeholder: 'Enter Your Email' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="col-md-8"><br>
  <h3>Edit This User</h3><br>

  <%= render 'form', user: @user %>

  <%= link_to 'Show this User', @user, class: 'btn btn-outline-info' %> 
  <%= link_to 'Back to all Users', users_path, class: 'btn btn-outline-primary' %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing of all Users</h3><br>
<div class="table-responsive">
  <table class="table table-condensed table-bordered">
    <thead>
      <tr class="table-info">
        <th>Name</th>
        <th>Email</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', user, class: 'btn btn-outline-info' %></td>
          <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-outline-warning' %></td>
          <td><%= link_to 'Delete User', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <br>

  <%= link_to 'Create a new User', new_user_path, class: 'btn btn-outline-primary' %><br><br>
  <%= link_to ' View all Posts', root_path, class: 'btn btn-outline-primary' %>

app/views/users/new.html.erb
<div class="col-md-8"><br>
  <h3>Create a new User</h3><br>

  <%= render 'form', user: @user %>

  <%= link_to 'Back to all Users', users_path, class: 'btn btn-outline-primary' %>
</div>

app/views/users/show.html.erb
<div class="col-md-8">
  <p id="notice"><%= notice %></p>
  <br>
  <p>
    <strong>Name of the User:</strong><br>
    <%= @user.name %>
  </p>

  <p>
    <strong>Users Email:</strong><br>
    <%= @user.email %>
  </p>
  <br>
  <%= link_to 'Edit this User', edit_user_path(@user), class: 'btn btn-outline-warning' %> 
  <%= link_to 'Back to all Users', users_path, class: 'btn btn-outline-primary' %>
</div>